two_pandas:
  observation_types:
    - pixels_agent_pos
  available_scenes:
    - ArmLevel
  available_tasks:
    - pickandplace
  action_space:
    actuator_names:
      - L_joint1
      - L_joint2
      - L_joint3
      - L_joint4
      - L_joint5
      - L_joint6
      - L_joint7
      - L_gripper
      - R_joint1
      - R_joint2
      - R_joint3
      - R_joint4
      - R_joint5
      - R_joint6
      - R_joint7
      - R_gripper
    actuator_limits:
      - name: L_joint1
        lower: -2.8973
        upper: 2.8973
      - name: L_joint2
        lower: -1.7628
        upper: 1.7628
      - name: L_joint3
        lower: -2.8973
        upper: 2.8973
      - name: L_joint4
        lower: -3.07179
        upper: -0.06979
      - name: L_joint5
        lower: -2.8973
        upper: 2.8973
      - name: L_joint6
        lower: -0.31421
        upper: 3.45579
      - name: L_joint7
        lower: -3.6826
        upper: 2.112
      - name: L_gripper
        lower: 0.0
        upper: 255.0
      - name: R_joint1
        lower: -2.8973
        upper: 2.8973
      - name: R_joint2
        lower: -1.7628
        upper: 1.7628
      - name: R_joint3
        lower: -2.8973
        upper: 2.8973
      - name: R_joint4
        lower: -3.07179
        upper: -0.06979
      - name: R_joint5
        lower: -2.8973
        upper: 2.8973
      - name: R_joint6
        lower: -0.31421
        upper: 3.45579
      - name: R_joint7
        lower: -3.6826
        upper: 2.112
      - name: R_gripper
        lower: 0.0
        upper: 255.0
  observation_space:
    actuator_names:
      - L_joint1
      - L_joint2
      - L_joint3
      - L_joint4
      - L_joint5
      - L_joint6
      - L_joint7
      - L_gripper
      - R_joint1
      - R_joint2
      - R_joint3
      - R_joint4
      - R_joint5
      - R_joint6
      - R_joint7
      - R_gripper
    actuator_limits:
      - name: L_joint1
        lower: -2.8973
        upper: 2.8973
      - name: L_joint2
        lower: -1.7628
        upper: 1.7628
      - name: L_joint3
        lower: -2.8973
        upper: 2.8973
      - name: L_joint4
        lower: -3.07179
        upper: -0.06979
      - name: L_joint5
        lower: -2.8973
        upper: 2.8973
      - name: L_joint6
        lower: -0.31421
        upper: 3.45579
      - name: L_joint7
        lower: -3.6826
        upper: 2.112
      - name: L_gripper
        lower: 0.0
        upper: 255.0
      - name: R_joint1
        lower: -2.8973
        upper: 2.8973
      - name: R_joint2
        lower: -1.7628
        upper: 1.7628
      - name: R_joint3
        lower: -2.8973
        upper: 2.8973
      - name: R_joint4
        lower: -3.07179
        upper: -0.06979
      - name: R_joint5
        lower: -2.8973
        upper: 2.8973
      - name: R_joint6
        lower: -0.31421
        upper: 3.45579
      - name: R_joint7
        lower: -3.6826
        upper: 2.112
      - name: R_gripper
        lower: 0.0
        upper: 255.0

unitreego1:
  observation_types:
    - agent_pos
  available_scenes:
    - velocity
  available_tasks:
    - locomotion
  action_space:
    actuator_names:
      - FR_hip_joint
      - FR_thigh_joint
      - FR_calf_joint
      - FL_hip_joint
      - FL_thigh_joint
      - FL_calf_joint
      - RR_hip_joint
      - RR_thigh_joint
      - RR_calf_joint
      - RL_hip_joint
      - RL_thigh_joint
      - RL_calf_joint
    actuator_limits:
      - name: FR_hip_joint
        lower: -0.863
        upper: 0.863
        default: 0.1
      - name: FR_thigh_joint
        lower: -0.686
        upper: 4.501
        default: 0.9
      - name: FR_calf_joint
        lower: -2.818
        upper: -0.888
        default: -1.8
      - name: FL_hip_joint
        lower: -0.863
        upper: 0.863
        default: -0.1
      - name: FL_thigh_joint
        lower: -0.686
        upper: 4.501
        default: 0.9
      - name: FL_calf_joint
        lower: -2.818
        upper: -0.888
        default: -1.8
      - name: RR_hip_joint
        lower: -0.863
        upper: 0.863
        default: 0.1
      - name: RR_thigh_joint
        lower: -0.686
        upper: 4.501
        default: 0.9
      - name: RR_calf_joint
        lower: -2.818
        upper: -0.888
        default: -1.8
      - name: RL_hip_joint
        lower: -0.863
        upper: 0.863
        default: -0.1
      - name: RL_thigh_joint
        lower: -0.686
        upper: 4.501
        default: 0.9
      - name: RL_calf_joint
        lower: -2.818
        upper: -0.888
        default: -1.8
  observation_space:
    actuator_names:
      - FR_hip_joint
      - FR_thigh_joint
      - FR_calf_joint
      - FL_hip_joint
      - FL_thigh_joint
      - FL_calf_joint
      - RR_hip_joint
      - RR_thigh_joint
      - RR_calf_joint
      - RL_hip_joint
      - RL_thigh_joint
      - RL_calf_joint
    actuator_limits:
      - name: FR_hip_joint
        lower: -0.863
        upper: 0.863
        default: 0.1
      - name: FR_thigh_joint
        lower: -0.686
        upper: 4.501
        default: 0.9
      - name: FR_calf_joint
        lower: -2.818
        upper: -0.888
        default: -1.8
      - name: FL_hip_joint
        lower: -0.863
        upper: 0.863
        default: -0.1
      - name: FL_thigh_joint
        lower: -0.686
        upper: 4.501
        default: 0.9
      - name: FL_calf_joint
        lower: -2.818
        upper: -0.888
        default: -1.8
      - name: RR_hip_joint
        lower: -0.863
        upper: 0.863
        default: 0.1
      - name: RR_thigh_joint
        lower: -0.686
        upper: 4.501
        default: 0.9
      - name: RR_calf_joint
        lower: -2.818
        upper: -0.888
        default: -1.8
      - name: RL_hip_joint
        lower: -0.863
        upper: 0.863
        default: -0.1
      - name: RL_thigh_joint
        lower: -0.686
        upper: 4.501
        default: 0.9
      - name: RL_calf_joint
        lower: -2.818
        upper: -0.888
        default: -1.8
